### PR TITLE
Use T.workspace in Git.open()

### PR DESCRIPTION
**Pull request by defung**
In mill 0.12, the following line fails because the workdir (`"."`) is now deep inside the mill-server directory, and that's not where we want to get the git repo from:

```
      val git            = Git.open(new File("."))
```

error:
```
om.goyeau.mill.git.GitVersionModule.version.super.GitVersionModule org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /opt/agent/runners/0aa8062bdb914a303-4/_work/defung/test-repo/out/mill-server/5872f4ddb9601f7e0e0e05b9e73414d9af91f4ba-1/sandbox
    org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:627)
    org.eclipse.jgit.api.Git.open(Git.java:93)
    org.eclipse.jgit.api.Git.open(Git.java:73)
    com.goyeau.mill.git.GitVersionModule$.$anonfun$version$2(GitVersionModule.scala:17)
```

Instead, we should be explicitly using `T.workspace` to get the root dir of the workspace.

### CODE REVIEW

**Comment by joan38** [comment]
Good catch @defung 
We just need a `./mill __.style` and we should be good

**Comment by defung** [comment]
@joan38 done!

File: build.sc [hunk 1]
```diff
@@ -7,12 +7,12 @@ import com.goyeau.mill.scalafix.StyleModule
 import de.tobiasroeser.mill.integrationtest._
 import mill._
 import mill.scalalib._
-import mill.scalalib.api.Util.scalaNativeBinaryVersion
+import mill.scalalib.api.ZincWorkerUtil.scalaNativeBinaryVersion
```
Comment (defung) [inline build.sc:10]: `Util` is deprecated

File: mill-git/src/com/goyeau/mill/git/GitVersionModule.scala [hunk 2]
```diff
@@ -35,19 +38,20 @@ object GitVersionModule extends ExternalModule {
                 if (isDirty) s"-${distance.toInt + 1}-${uncommitted()}"
                 else s"-$distance-${hash.take(hashLength)}$snapshotSuffix"
               }
-              s"$tag$distanceHash"
+              MillSuccess(s"$tag$distanceHash")
             case untaggedRegex(hash) =>
-              if (isDirty) uncommitted()
-              else s"${hash.take(hashLength)}$snapshotSuffix"
-            case _ => throw new IllegalStateException(s"Unexpected git describe output: $description")
```
Comment (defung) [inline mill-git/src/com/goyeau/mill/git/GitVersionModule.scala:42]: `./mill __.style` doesn't like `throw new...`, so changed this up to use pattern matching instead of `fold`

File: mill-git/src/com/goyeau/mill/git/GitVersionModule.scala [hunk 3]
```diff
@@ -61,5 +65,5 @@ object GitVersionModule extends ExternalModule {
     cache.writeTree(altGit.getRepository.newObjectInserter()).abbreviate(hashLength).name()
   }
 
-  override lazy val millDiscover: Discover[this.type] = Discover[this.type]
```
Comment (defung) [inline mill-git/src/com/goyeau/mill/git/GitVersionModule.scala:64]: `Discover` in mill 0.12.x no longer take a type parameter:

```
[130/142] mill-git[0.12.4].compile
[info] compiling 1 Scala source to /Users/dennis.fung/repos/defung/mill-git/out/mill-git/0.12.4/compile.dest/classes ...
[error] /Users/defung/repos/joan38/mill-git/mill-git/src/com/goyeau/mill/git/GitVersionModule.scala:68:35: mill.define.Discover does not take type parameters
[error]   override lazy val millDiscover: Discover[this.type] = Discover[this.type]
[error]                                   ^
[error] one error found
1 targets failed
mill-git[0.12.4].compile Compilation failed
```

File: build.sc (hunk 1 above)
Comment (defung) [reply build.sc:10]: https://github.com/com-lihaoyi/mill/blob/7f073d11df739c34b832eb6333500c65e26c63da/scalalib/api/src/mill/scalalib/api/ZincWorkerUtil.scala#L155

File: .github/workflows/ci.yml [hunk 4]
```diff
@@ -20,7 +20,7 @@ jobs:
       - name: Checks
         run: |
           git config --global user.name "CI"
-          ./mill all __.checkStyle __.docJar __.test
+          ./mill all __.checkStyle __.docJar __.publishLocal __.test
```
Comment (defung) [inline .github/workflows/ci.yml:23]: needed `__.publishLocal` in order for it to work with mill 0.12 for some reason

**Review by joan38 — APPROVED** [review]
